# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Paso de construcción
        run: echo "Este paso es el de construcción"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Paso de testeo
        run: echo "Este paso es el de construcción"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Paso de deploy
        run: echo "Este paso es de despliegue"